language: nix
env:
    matrix:
      - TARGET="rmPkgs.linuxPackages.mxc_epdc_fb_damage"
      - TARGET="rmPkgs.rM-vnc-server"
      - TARGET="hostPkgs.gst-libvncclient-rfbsrc"
script:
    - nix-build --arg release true -A $TARGET

