name: 'nix-remarkable'
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v6
      with:
        name: nix-remarkable
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build --arg release true -f . rmPkgs.linuxPackages.mxc_epdc_fb_damage 
    - run: nix build --arg release true -f . rmPkgs.rM-vnc-server
